-- ============================================================================
-- /enrich — crm_leads PATCH field mapping (ACTIVE)
--
-- This is the live contract crm-leads-patch.md and tools/crm-leads-update.js
-- both use. No ALTER TABLE is needed -- every enrichable field reuses an
-- existing crm_leads column or lives inside lead_source_description (json).
--
-- Direction of data flow is the opposite of a sibling project's /jobs and
-- /posts: those INSERT new rows through a custom extension endpoint
-- (x-crm-leads-secret header). This flow only ever PATCHes a row that
-- already exists, through Directus's native REST endpoint (Bearer token) --
-- see .env.example for why these are separate env vars even on the same host.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Allow-listed PATCH keys — enforced in tools/crm-leads-update.js's
-- ALLOWED_TOP_KEYS, not just documented here. Anything not in this list is
-- stripped from the request body before it is ever sent.
--
-- SHAPE / TYPE / VALIDATION of each allow-listed value is a second, separate
-- gate, driven by schemas/CRM_Leads_Field_Reference.json (the CRM's own
-- column catalogue: field_type + validation regex + enumerated options).
-- tools/crm-leads-update.js loads that file and checks every value it is
-- about to send; a value that does not fit its column is DROPPED and
-- reported in `invalid_keys`, never sent. In particular:
--   * employees (Integer)     -> must be a whole number. A "Company size"
--                                range like "51-200 employees" is NOT valid;
--                                crm-leads-patch.md must reduce it to an
--                                integer (the lower bound) or omit the field.
--                                A clean numeric string ("200") is coerced.
--   * firstname / lastname     -> column regex ^[a-zA-Z ]*$ (ASCII letters and
--                                spaces only — no hyphens, apostrophes,
--                                accents, periods). A name that doesn't fit is
--                                dropped; send only a form that already fits or
--                                omit it and put the real name in description.
--   * secondary_email          -> column regex is a standard email pattern.
--   * tags (JSON)              -> must be a JSON array of strings.
--   * lead_source_description  -> must be a JSON object.
-- If CRM_Leads_Field_Reference.json cannot be loaded, the tool fails closed
-- (no PATCH) rather than sending unvalidated.
-- ----------------------------------------------------------------------------
-- organization_name, website, organization_linkedin, employees  -> company
--                                                                    facts found on the job/post/company page
-- industry (UUID lookup)                                         -> ONLY when the company page's stated
--                                                                    "Industry" label confidently matches one
--                                                                    of CRM_Leads_Field_Reference.json's 16
--                                                                    enumerated labels (Service Provider,
--                                                                    ManagementISV, MSP, ERP, Large Enterprise,
--                                                                    etc.) -- send the matching **id**, never
--                                                                    the label text. LinkedIn's own industry
--                                                                    taxonomy rarely lines up exactly with this
--                                                                    legacy list, so most leads legitimately
--                                                                    get no match -- omit the field rather than
--                                                                    pick the closest-sounding one. The raw
--                                                                    industry text is still folded into `tags`
--                                                                    regardless of whether a confident id match
--                                                                    exists, so nothing is lost either way.
-- firstname, lastname, title, linkedin                          -> the resolved poster's identity (see
--                                                                    "Reshare resolution" below) -- the
--                                                                    ORIGINAL poster for a resolved reshare,
--                                                                    never the resharer. `linkedin` is that
--                                                                    person's own profile URL, written only
--                                                                    under the same identity-confidence gate as
--                                                                    firstname/lastname (never for an
--                                                                    unconfirmed first-profile-link guess) --
--                                                                    see the note below this list; `linkedin`
--                                                                    is also still read as a scrape-candidate
--                                                                    input earlier in the flow, independent of
--                                                                    this write
-- lead_source                                                    -> ALWAYS DERIVED by
--                                                                    tools/crm-leads-update.js from the lead's
--                                                                    own job_posting_url (passed as
--                                                                    --job-posting-url, never part of the JSON
--                                                                    body), matched by domain against
--                                                                    CRM_Leads_Field_Reference.json's
--                                                                    lead_source enum and looked up by LABEL
--                                                                    (never a hardcoded id) -- see
--                                                                    classifyLeadSourceId(). Every
--                                                                    job_posting_url this flow sees is a
--                                                                    LinkedIn URL, so this resolves to the
--                                                                    "LinkedIn" option in practice, but the
--                                                                    code actually checks rather than assuming:
--                                                                    an empty/"not available"/unrecognized URL
--                                                                    means no `lead_source` in that patch at
--                                                                    all, never a guess. crm-leads-patch.md
--                                                                    does not compute or include this value
--                                                                    itself -- it only passes the URL through
-- description                                                    -> the job/post's OWN description text
--                                                                    (from main_text/job_page.main_text) when
--                                                                    the row's existing value is empty/"not
--                                                                    available". Once real content already
--                                                                    exists there (usually from insert time),
--                                                                    enrichment instead APPENDS a short 1-2
--                                                                    sentence note about what it confirmed --
--                                                                    never a wholesale replacement
-- primary_email, secondary_email, phone, mobile, whatsapp
--                                                                 -> the resolved POSTER's own contact info,
--                                                                    only when literally visible in scraped
--                                                                    text -- LinkedIn does not expose
--                                                                    email/phone by default, so these
--                                                                    legitimately stay untouched ("not
--                                                                    available") on most rows. That is a
--                                                                    correct outcome, not a failed run.
--                                                                    `phone` alone has one documented fallback:
--                                                                    the company's own About-tab number when
--                                                                    the poster's personal contact isn't found
--                                                                    (never mobile/whatsapp, which imply a
--                                                                    personal device) -- see phone_source below
-- google_chat, instagram, facebook, teams_id                     -> the resolved POSTER'S OWN handles, never
--                                                                    the company's -- ONLY a literal handle/URL
--                                                                    actually present on their profile
--                                                                    (profile_page.main_text /
--                                                                    contact_info_text) or stated in their own
--                                                                    post/job text, the same evidence-only rule
--                                                                    as `website`. A company's social links on
--                                                                    company_page are NOT these fields.
--                                                                    LinkedIn essentially never surfaces a
--                                                                    Teams id or Google Chat handle, so
--                                                                    `teams_id`/`google_chat` will almost
--                                                                    always legitimately stay untouched --
--                                                                    included for the rare case this specific
--                                                                    person's page states one directly, never
--                                                                    guessed.
-- city, street, zipcode                                          -> address, only when literally present
-- country, state (UUID lookups)                                  -> ONLY when the company page's
--                                                                    "Headquarters" text confidently names one
--                                                                    of the enumerated country/state labels --
--                                                                    send the matching **id**, never the label.
--                                                                    `country`'s 15 labels are each unique, so
--                                                                    a clear textual match is safe. `state`'s
--                                                                    list has genuine DUPLICATE labels with
--                                                                    different ids (as of this file: "Illinois",
--                                                                    "Georgia", "Telangana", and "Maharashtra"
--                                                                    each appear twice) -- a CRM data-quality
--                                                                    issue this flow cannot resolve from
--                                                                    LinkedIn text alone. When the matched
--                                                                    label is ambiguous like that, omit `state`
--                                                                    entirely rather than guess between the ids
--                                                                    (the city/country still get their own
--                                                                    unambiguous fields).
-- tags (json)                                                     -> the Industry label (above) PLUS any
--                                                                    skills/technologies/role keywords
--                                                                    literally named in the job/post text (the
--                                                                    same signal lead_source_description.
--                                                                    skills_in_jd already captures at insert
--                                                                    time, landing in this column too) --
--                                                                    merged (union, deduped), never replaced
-- lead_source_description (json)                                 -> merged, see shape below -- never a
--                                                                    full-object replace
--
-- Never sent, on purpose:
--   lead_status                    -- pipeline status, not an enrichment fact.
--   primary_bde / secondary_bde    -- assignment, not an enrichment fact.
--   recommended_for_outreach       -- a scoring decision made at insert time -- this flow does not re-score.
--   is_ai_generated / job_source_type
--                                  -- identity of the row, never rewritten.
--   job_posting_url                -- identity of the row (which URL it was inserted from), never rewritten.
--   email_opt_out                  -- compliance flag, never touched by automation.
-- All of the above except `industry`/`country`/`state` are absent from
-- CRM_Leads_Field_Reference.json entirely; those three ARE present there (as
-- valid, generally-updatable CRM columns) but are still hard-excluded here
-- for the row-identity/assignment reasons above -- being a valid column is
-- necessary but not sufficient to be enrichment-writable. `job_posting_url`
-- is under this same "valid column, still excluded" treatment.
--
-- `lead_source` and `linkedin` used to be excluded under this same
-- "identity, fixed at insert time" reasoning. Both are now WRITTEN, per
-- explicit instruction -- see the active mapping list above for how each is
-- populated (one a code-derived value from job_posting_url, the other
-- agent-judged evidenced content). `job_posting_url` remains excluded; only
-- the URL a row was *inserted* with is off-limits, not the poster's own
-- resolved profile URL or a domain-based read of that same URL.

-- ----------------------------------------------------------------------------
-- lead_source_description (json) — merge behavior
-- Flexible on purpose (plain json, no CHECK constraint), same as the sibling
-- project's insert-time shape. crm-leads-patch.md reads the lead's EXISTING
-- lead_source_description first and merges into it -- it never sends a bare
-- replacement object, which would silently drop keys the insert flow wrote
-- (job_title, work_mode, skills_in_jd, the five scores, etc.).
-- ----------------------------------------------------------------------------
-- {
--   ... every key already there, untouched ...
--   "source_urls": [...],                 -- APPENDED: every URL actually
--                                             visited this run (source +
--                                             profile hop + company hop),
--                                             deduplicated against what was
--                                             already there
--   "enriched_at": "2026-09-09T12:00:00Z",  -- ISO timestamp of this PATCH
--   "enrichment_outcome": "enriched",       -- enriched | partial | no-new-data
--                                             | resharer-fallback
--   "identity_confidence": "original-post"  -- present only for a Post lead:
--                                             "original-post" | "resharer-fallback"
--   "phone_source": "company_about_page"     -- present only when `phone` was filled from the
--                                             company's About-tab phone number because the
--                                             poster's own contact info wasn't found -- marks it
--                                             as NOT a personal number
-- }

-- ----------------------------------------------------------------------------
-- Reshare resolution
-- ----------------------------------------------------------------------------
-- A LinkedIn "X reposted this" wrapper means the resharer is NOT the hiring
-- contact -- the embedded original post's author is. lead-url-enrich.md
-- always prefers original_post.poster over reposted_by when
-- tools/linkedin-enrich-scrape.js returns both. If only a resharer identity
-- could be captured (original post deleted/private/unreadable),
-- firstname/lastname/title/linkedin may fall back to the resharer, but
-- lead_source_description.identity_confidence must then read
-- "resharer-fallback" -- never silently presented as the same confidence as
-- a genuine original-poster match.

-- ============================================================================
-- Setup needed before this flow can PATCH crm_leads
-- ============================================================================

-- 1. A Directus static access token (or a role/user token) with read access
--    to crm_leads (GET /items/crm_leads) and update access (PATCH
--    /items/crm_leads/{id}). This is a different credential than a sibling
--    project's CRM_LEADS_API_SECRET (that one authenticates a custom
--    extension route with a header the extension itself checks; this token
--    authenticates directly against Directus's own permission system).
--    Set as CRM_ENRICH_API_TOKEN.

-- 2. CRM_ENRICH_API_URL -- the Directus base URL, e.g. https://directus.example.com
--    (no /items/... suffix -- the tools append that themselves).

-- 3. Confirm Directus's date_created system field is actually enabled on
--    crm_leads (Data Model -> crm_leads -> date_created field). If it is not,
--    tools/crm-leads-fetch.js's filter[date_created][_gte] will not do
--    anything useful and the fetch window needs a different field -- update
--    this file and tools/crm-leads-fetch.js together if so.
